version: '2'

services:
  nagios:
    image: polster/docker-nagios:latest
    container_name: nagios
    volumes:
      - nagios_data:/usr/local/nagios
    ports:
      - "8090:80"

volumes:
  nagios_data:
